# Generated by Django 5.0.2 on 2024-02-18 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '❤️'), (2, '❤️❤️'), (3, '❤️❤️❤️'), (4, '❤️❤️❤️❤️'), (5, '❤️❤️❤️❤️❤️')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
